DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS links;

CREATE TABLE IF NOT EXISTS links (
    id INTEGER PRIMARY KEY,
    link1 TEXT NOT NULL,
    link2 TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS books (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT UNIQUE NOT NULL,
  score INTEGER NOT NULL
);
